[package]
name = "arduino-monitor-gtk"
version = "0.1.0"
authors = ["receek <krzysztof.juszczyk20@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.8.0"
gio = "0.8.0"
glib = "^0"